server:
  port: 8081
  servlet-path: /product 
  
spring:
  application:
    name: eureka-client1


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8080/eureka